import { useEffect } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { fadeUpView } from "@/lib/motionVariants";
import { trackEvent } from "@/lib/trackEvent";

const SECTIONS = [
  {
    title: "What DABAR Is",
    body:
      "DABAR is a tool for personal scripture reflection. It is not a church, a pastor, or a source of doctrinal authority. Responses are aids to personal reflection — not pastoral counsel or theological instruction.",
  },
  {
    title: "Theological Position",
    body:
      "DABAR is broadly Protestant and evangelical. We hold to the authority of scripture, the Trinity, and salvation by grace through faith. We are intentionally neutral on eschatology, baptism mode, charismatic gifts, and Calvinist/Arminian distinctions — so believers across denominations can use DABAR freely.",
  },
  {
    title: "AI Disclosure",
    body:
      "Responses are generated by Claude (Anthropic). They are AI-assisted reflection prompts, not infallible guidance. Scripture references are drawn from standard translations and should always be verified in your own Bible.",
  },
  {
    title: "Known Limitations",
    body:
      "AI can occasionally misattribute or paraphrase scripture. If you encounter an inaccurate response, please use the feedback mechanism on any response or email mike@dabarbible.com.",
  },
  {
    title: "Report an Inaccuracy",
    body:
      "See something theologically inaccurate? Tap the flag icon on any response or email mike@dabarbible.com. We review every report.",
  },
  {
    title: "What DABAR Is Not",
    body:
      "DABAR is not pastoral counsel. It is not a substitute for your local church or a licensed counsellor. If you are in crisis, please contact the 988 Suicide and Crisis Lifeline by calling or texting 988.",
  },
];

export default function DoctrinePage() {
  useEffect(() => {
    trackEvent("doctrine_page_viewed", { screen: "doctrine" });
  }, []);

  return (
    <div className="min-h-screen px-6 py-12 max-w-2xl mx-auto">
      <Link
        to="/"
        className="text-sm font-body text-muted-foreground hover:text-foreground transition-colors mb-8 inline-block"
      >
        ← Back
      </Link>

      <motion.div {...fadeUpView(0)} className="text-center mb-12">
        <h1 className="font-serif text-3xl sm:text-4xl text-foreground tracking-wide mb-3">
          What We Believe
        </h1>
        <p className="font-body text-sm text-muted-foreground tracking-wide">
          Doctrinal statement &amp; AI disclosure
        </p>
        <div className="w-12 h-px bg-gold mx-auto mt-6" />
      </motion.div>

      <div className="space-y-10">
        {SECTIONS.map((section, i) => (
          <motion.section
            key={section.title}
            {...fadeUpView(0.05 + i * 0.08)}
          >
            <h2 className="font-serif text-xl text-gold tracking-wide mb-3">
              {section.title}
            </h2>
            <p className="font-body text-base text-foreground/85 leading-relaxed">
              {section.body}
            </p>
          </motion.section>
        ))}
      </div>

      <div className="w-12 h-px bg-gold mx-auto mt-16 mb-6" />
      <p className="font-body text-xs text-muted-foreground text-center">
        Questions? Contact{" "}
        <a
          href="mailto:mike@dabarbible.com"
          className="text-gold hover:underline"
        >
          mike@dabarbible.com
        </a>
      </p>
    </div>
  );
}