import { Link } from "react-router-dom";
import { Flame } from "lucide-react";
import SEO from "@/components/SEO";

const MuseConnectorPage = () => {
  return (
    <>
      <SEO
        title="DaBarBible Connector for Muse"
        description="The DaBarBible connector lets Meta's Muse AI agent share a King James Version Bible verse when someone asks for one — by theme, or today's verse."
        canonical="https://dabarbible.com/muse"
      />
      <div className="min-h-screen px-6 py-12 max-w-2xl mx-auto">
        <Link to="/" className="flex items-center gap-2 text-gold hover:text-gold-dark transition-colors mb-10">
          <Flame size={16} strokeWidth={1.5} />
          <span className="font-serif text-sm tracking-widest uppercase">Dabar</span>
        </Link>

        <h1 className="font-serif text-3xl text-foreground tracking-wide mb-2">DaBarBible Connector for Muse</h1>
        <p className="font-body text-xs text-muted-foreground uppercase tracking-wider mb-8">
          Technical reference
        </p>
        <div className="w-12 h-px bg-gold mb-8" />

        <div className="space-y-6 font-body text-sm text-foreground/90 leading-relaxed">
          <p>
            The DaBarBible connector lets Meta's Muse AI agent share a King James Version Bible verse when someone asks
            for one — by theme, or today's verse.
          </p>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Endpoint</h2>
            <p>
              Remote MCP server (Streamable HTTP, JSON-RPC 2.0):{" "}
              <code className="font-mono text-xs text-gold break-all">
                https://crkkimoblnrxpszehmkg.supabase.co/functions/v1/muse-verses
              </code>
              <br />
              No sign-in, API key or account is required.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Tool: get_verse (read-only)</h2>
            <ul className="space-y-2 list-none">
              <li className="flex items-start gap-2"><span className="text-gold mt-0.5">·</span>Input: optional <code className="font-mono text-xs text-gold">theme</code> — one of: peace, anxiety, fear, strength, hope, grief, guidance, love, rest, joy, renewal, trust.</li>
              <li className="flex items-start gap-2"><span className="text-gold mt-0.5">·</span>With no theme, returns today's verse (the same verse as DaBarBible's daily verse email).</li>
              <li className="flex items-start gap-2"><span className="text-gold mt-0.5">·</span>Output: <code className="font-mono text-xs text-gold">reference</code>, <code className="font-mono text-xs text-gold">text</code>, <code className="font-mono text-xs text-gold">translation</code> ("KJV"), <code className="font-mono text-xs text-gold">theme</code>, and <code className="font-mono text-xs text-gold">link</code> (dabarbible.com).</li>
              <li className="flex items-start gap-2"><span className="text-gold mt-0.5">·</span>Verse text is quoted word for word from the public-domain King James Version stored by DaBarBible. It is not generated by AI.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Example request</h2>
            <pre className="font-mono text-xs text-foreground/80 bg-foreground/5 rounded-sm p-4 overflow-x-auto"><code>{`{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"get_verse","arguments":{"theme":"peace"}}}`}</code></pre>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Example response (structuredContent)</h2>
            <pre className="font-mono text-xs text-foreground/80 bg-foreground/5 rounded-sm p-4 overflow-x-auto"><code>{`{"reference":"John 14:27","text":"Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.","translation":"KJV","theme":"peace","link":"https://dabarbible.com/?utm_source=muse&utm_medium=connector&utm_campaign=get_verse"}`}</code></pre>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Errors</h2>
            <p>
              An unknown theme returns a tool error listing the valid themes. Other failures return a generic
              "Verse unavailable right now" message.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Privacy</h2>
            <p>
              The connector does not receive or store any personal information. For each request we record only the
              theme asked for and the time, to count usage. See our{" "}
              <Link to="/privacy" className="text-gold hover:underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground tracking-wide mb-3">Support</h2>
            <p>
              Questions:{" "}
              <Link to="/support" className="text-gold hover:underline">dabarbible.com/support</Link>
            </p>
          </section>
        </div>

        <div className="mt-16 text-center">
          <Link
            to="/"
            className="font-serif tracking-widest text-sm uppercase px-8 py-3 border border-gold text-gold rounded-sm hover:bg-gold hover:text-primary-foreground transition-all"
          >
            Return to Dabar
          </Link>
        </div>
      </div>
    </>
  );
};

export default MuseConnectorPage;
